version: '3'
services:

  database:
    image: mysql:8.0.35
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
    working_dir: /var/www
    image: my-app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  artisan:
    image: my-app
    command: php artisan migrate
    volumes:
      - ./:/var/www
    depends_on:
      database:
        condition: service_healthy
